# прозрачность
background_opacity 0.85

# курсор
cursor_shape block
cursor_blink_interval 0

# отступы
window_padding_width 10

# скругления (визуально через hyprland)
# (kitty сам не делает rounding)

# цвета (пример)
foreground #cdd6f4
background #1e1e2e

selection_background #f5e0dc
selection_foreground #1e1e2e

font_family JetBrainsMono Nerd Font
font_size 12

shell zsh
